#!/bin/bash

percentage() {
  charge= upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}'
  echo "$charge"
}

status() {
  status= upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}'
  echo "$status"
}

echo "$(percentage) $(status)"
