#!/bin/bash

percentage() {
  charge= upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}'
  echo "$charge"
}

status() {
  status= upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}'
  echo "$status"
}

p="$(percentage | sed 's/%//')"
s="$(status)"
if [[ "$p" -lt 25 && "$s" != "charging" ]]; then
  dunstify -u ciritcal "Battery low"
fi
echo "$p% $s"
