[font]
normal={family="JetBrainsMono", style="Regular"}
bold={family="JetBrainsMono", style="Bold"}
italic={family="JetBrainsMono", style="Italic"}
bold_italic={family="JetBrainsMono", style="Regular"}
size=14
