[font]
normal={family="JetBrainsMonoNerdFont", style="Regular"}
bold={family="JetBrainsMonoNerdFont", style="Bold"}
italic={family="JetBrainsMonoNerdFont", style="Italic"}
bold_italic={family="JetBrainsMonoNerdFont", style="Regular"}
size=11.5
[terminal]
shell = { program = "/bin/fish", args = ["-c", "zellij"] }
# shell = { program = "/bin/fish" }
[window]
padding = {x = 5, y = 5}
